In [ ]:
import numpy as np
from scipy.linalg import circulant
from numpy import random
import math
def text_to_array(plaintext):
  val = {
    'A': 0,
    'B': 1,
    'C': 2,
    'D': 3,
    'E': 4,
    'F': 5,
    'G': 6,
    'H': 7,
    'I': 8,
    'J': 9,
    'K': 10,
    'L': 11,
    'M': 12,
    'N': 13,
    'O': 14,
    'P': 15,
    'Q': 16,
    'R': 17,
    'S': 18,
    'T': 19,
    'U': 20,
    'V': 21,
    'W': 22,
    'X': 23,
    'Y': 24,
    'Z': 25
    }
  texttoarrays = []
  for i in range(len(plaintext)):
      letter=plaintext[i]
      texttoarrays.append(val[letter])
  texttoarrays1 = np.transpose(texttoarrays)
  return texttoarrays1

def get_public_key(n):
  while True:
        arr = np.random.randint(10, size=(n, n))
        gc = np.array([np.roll(row, -i) for i, row in enumerate(arr)])
        det_gc = np.linalg.det(gc)
        if np.isclose(det_gc, 0):
            return arr
  #arr = random.randint(100 , size = (2,2))
  #gc = circulant()
  #det = np.linalg.det(gc)
  #matrix = np.random.randint(2, size=(n, n))
  #key = np.linalg.matrix_power(matrix, n-1)[0]
def get_secret_key(n):
  while True:
      arr = np.random.randint(100, size=n)
      for i in range(n-1):
        for j in range(i+1, n):
            if np.gcd(arr[i], arr[j]) == 1:
              g = circulant(arr)
              return g
def generate_main_key(pub,sec):
  ag = np.matmul(sec,pub)
  ainv = np.linalg.inv(sec)
  k = np.matmul(ag,ainv)
  key = np.floor(k % 26)
  return key
def hill_cipher_encrypt(textarray, key, sec):
  cipher1 = np.matmul(key, textarray)
  first_clmn = sec[:,0]
  pre_cipher = np.add(cipher1, first_clmn)
  final = pre_cipher % 26
  val = {
    'A': 0,
    'B': 1,
    'C': 2,
    'D': 3,
    'E': 4,
    'F': 5,
    'G': 6,
    'H': 7,
    'I': 8,
    'J': 9,
    'K': 10,
    'L': 11,
    'M': 12,
    'N': 13,
    'O': 14,
    'P': 15,
    'Q': 16,
    'R': 17,
    'S': 18,
    'T': 19,
    'U': 20,
    'V': 21,
    'W': 22,
    'X': 23,
    'Y': 24,
    'Z': 25
    }
  encrypted_msg = ''
  key_list = list(val.keys())
  val_list = list(val.values())
  for i in range(0,len(final)):
    num=final[i]
    pos = val_list.index(num)
    encrypted_msg+=key_list[pos]
  return pre_cipher, final, encrypted_msg

def hill_cipher_decrypt(sec2, key, sec):
  first_clmn = sec[:,0]
  inv_key = np.linalg.inv(key)
  decrypted_block = np.round_(np.matmul(inv_key, np.subtract(sec2, first_clmn)))

  val = {
    'A': 0,
    'B': 1,
    'C': 2,
    'D': 3,
    'E': 4,
    'F': 5,
    'G': 6,
    'H': 7,
    'I': 8,
    'J': 9,
    'K': 10,
    'L': 11,
    'M': 12,
    'N': 13,
    'O': 14,
    'P': 15,
    'Q': 16,
    'R': 17,
    'S': 18,
    'T': 19,
    'U': 20,
    'V': 21,
    'W': 22,
    'X': 23,
    'Y': 24,
    'Z': 25
    }
  decrypted_msg = ''
  key_list = list(val.keys())
  val_list = list(val.values())
  for i in range(0,len(decrypted_block)):
    num = math.floor(decrypted_block[i])
    pos = val_list.index(num)
    decrypted_msg+=key_list[pos]
  return decrypted_block, decrypted_msg

def main():
  # Key Generation
  plaintext = "BRUH"
  array = text_to_array(plaintext)
  public_key = get_public_key(len(plaintext))
  secret_key = get_secret_key(len(plaintext))
  main_key = generate_main_key(public_key, secret_key)
  # Encrypt the plaintext to form ciphertext.
  pre_cipher, cipher, ciphertext = hill_cipher_encrypt(array, main_key, secret_key)
  # Decrypt the ciphertext to form plaintext.
  decrypted_block, decrypted_msg = hill_cipher_decrypt(pre_cipher, main_key, secret_key)
  # Print the results.
  print("Plaintext:", plaintext)
  print("Array of the text : ",array)
  print("Public key : ",public_key)
  print("Secret key : ",secret_key)
  print("Main key : ",main_key)
  print("Cipher : ",cipher)
  print("The encrypted text is ",ciphertext)
  print("Secret Key 2 : ",pre_cipher)
  print("sub value : ",)
  print("After Decryption : ",decrypted_block)
  print("Message after decryption : ",decrypted_msg)
if __name__ == "__main__":
  main()

Plaintext: BRUH
Array of the text :  [ 1 17 20  7]
Public key :  [[6 6 4 5]
 [0 6 6 3]
 [7 8 7 7]
 [6 7 0 6]]
Secret key :  [[ 8 64  5 84]
 [84  8 64  5]
 [ 5 84  8 64]
 [64  5 84  8]]
Main key :  [[25.  7. 12. 24.]
 [ 2.  9. 10.  1.]
 [23.  1. 14.  4.]
 [ 2. 10. 10.  1.]]
Cipher :  [14.  4. 15.  1.]
The encrypted text is  OEPB
Secret Key 2 :  [560. 446. 353. 443.]
sub value : 
After Decryption :  [ 1. 17. 20.  7.]
Message after decryption :  BRUH


In [ ]:
import numpy as np

def admm_optimization(rho, max_iterations):
    # Initialize variables
    x = 0  # Initial value of x
    y = 0  # Initial value of y
    z = 0  # Initial value of z
    lambda_val = 0  # Initial value of the Lagrange multiplier

    # ADMM iterations
    for iteration in range(max_iterations):
        # Update x
        x = (z - y - lambda_val/rho) / 2

        # Update y
        y = (z - x - lambda_val/rho) / 2

        # Update z
        z = (x + y)

        # Update the Lagrange multiplier
        lambda_val = lambda_val + rho * (x + y - z)

    return x, y

# Define problem parameters
rho = 1  # Penalty parameter
max_iterations = 100  # Maximum number of ADMM iterations

# Solve the optimization problem using ADMM
x_optimal, y_optimal = admm_optimization(rho, max_iterations)

# Print the optimal values of x and y
print("Optimal value of x:", x_optimal)
print("Optimal value of y:", y_optimal)


Optimal value of x: 0.0
Optimal value of y: 0.0


In [ ]:
import numpy as np
from scipy.linalg import circulant
from numpy import random
import math
def get_secret_key(n):
  while True:
      arr = np.random.randint(10, size=n)
      for i in range(n-1):
        for j in range(i+1, n):
            if np.gcd(arr[i], arr[j]) == 1:
              g = circulant(arr)
              return g

print(get_secret_key(3))

[[5 0 9]
 [9 5 0]
 [0 9 5]]


In [ ]:
import numpy as np

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def generate_key_matrices(n, p):
    while True:
        A = np.random.randint(1, p, size=(n, n))
        if gcd(np.linalg.det(A), p) == 1:
            break

    while True:
        P = np.random.permutation(np.eye(n))
        if np.linalg.det(P) % p != 0:
            break

    return A, P

def hill_cipher_encrypt(plaintext, A, P, p):
    n = A.shape[0]
    m = len(plaintext) % n

    if m != 0:
        padding = n - m
        plaintext += 'X' * padding

    plaintext = [ord(c) - ord('A') for c in plaintext]

    ciphertext = ''
    for i in range(0, len(plaintext), n):
        block = np.array(plaintext[i:i+n]).reshape(n, 1)
        encrypted_block = (np.dot(A, np.dot(P, block))) % p
        encrypted_block = ''.join([chr(int(c) % p + ord('A')) for c in encrypted_block.flatten()])
        ciphertext += encrypted_block

    return ciphertext

def hill_cipher_decrypt(ciphertext, A, P, p):
    n = A.shape[0]
    A_inv = np.linalg.inv(A)
    P_inv = np.linalg.inv(P)

    plaintext = ''
    for i in range(0, len(ciphertext), n):
        block = np.array([ord(c) - ord('A') for c in ciphertext[i:i+n]]).reshape(n, 1)
        decrypted_block = (np.dot(P_inv, np.dot(A_inv, block))) % p
        decrypted_block = ''.join([chr(int(c) + ord('A')) for c in decrypted_block.flatten()])
        plaintext += decrypted_block

    return plaintext

# Example usage
plaintext = 'HELLO'
n = 3
p = 26

A, P = generate_key_matrices(n, p)
print("A, B")
ciphertext = hill_cipher_encrypt(plaintext, A, P, p)
print("Ciphertext:", ciphertext)

decrypted_plaintext = hill_cipher_decrypt(ciphertext, A, P, p)
print("Decrypted plaintext:", decrypted_plaintext)


A, B
Ciphertext: FPMXZK
Decrypted plaintext: AAZBXB
